OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: hf.excite.ph
    Specs:
      - Hostname: orderer
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Peers
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.hf.excite.ph
    Template:
      Count: 1
    Users:
      Count: 1