OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererOrg
    Domain: exciteph.com
    Specs:
      - Hostname: ordererorg
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Peers
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.exciteph.com
    Template:
      Count: 1
    Users:
      Count: 1