#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  default: 

services:
  # Certificate Authority
  ca.org1.hf.excite.ph:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hf.excite.ph
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.excite.ph-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e18ac7f58eafb2a82dd2a4ff4f89900f26b47bfa16a2bc071679d951702e5b87_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.excite.ph-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e18ac7f58eafb2a82dd2a4ff4f89900f26b47bfa16a2bc071679d951702e5b87_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fixtures/crypto-config/peerOrganizations/org1.hf.excite.ph/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.hf.excite.ph
    networks:
      default:
        aliases:
          - ca.org1.hf.excite.ph
  # Orderer
  orderer.hf.excite.ph:
    container_name: orderer.hf.excite.ph
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISPROFILE=Points
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=hf.excite.ph
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./fixtures/artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
        - ./fixtures/crypto-config/ordererOrganizations/hf.excite.ph/orderers/orderer.hf.excite.ph/msp:/var/hyperledger/orderer/msp
        - ./fixtures/crypto-config/ordererOrganizations/hf.excite.ph/orderers/orderer.hf.excite.ph/tls:/var/hyperledger/orderer/tls
    networks:
      default:
        aliases:
          - orderer.hf.excite.ph
  # Peers
  peer0.org1.hf.excite.ph:
    container_name: peer0.org1.hf.excite.ph
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_LOGGING_PEER=DEBUG
      - CORE_PEER_ADDRESS=peer0.org1.hf.excite.ph:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ID=peer0.org1.hf.excite.ph
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hf.excite.ph:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.excite.ph
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_NETWORKID=thanksapp
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.hf.excite.ph
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./fixtures/crypto-config/peerOrganizations/org1.hf.excite.ph/peers/peer0.org1.hf.excite.ph/msp:/var/hyperledger/msp
        - ./fixtures/crypto-config/peerOrganizations/org1.hf.excite.ph/peers/peer0.org1.hf.excite.ph/tls:/var/hyperledger/tls
    depends_on:
      - orderer.hf.excite.ph
    links:
      - orderer.hf.excite.ph
    networks:
      default:
        aliases:
          - peer0.org1.hf.excite.ph